spring:
  profiles:
    active: "test"
  config:
    import: db-test.properties
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-on-validation-error: true
  jpa:
    generate-ddl: false
    show-sql: false
    properties.hibernate:
      enable_lazy_load_no_trans: true
      globally_quoted_identifiers: true
      globally_quoted_identifiers_skip_column_definitions: true
    open-in-view: false
  github_for_issues:
    repo: nerds-odd-e/doughnut_sandbox
    token: ${GITHUB_FOR_ISSUES_API_TOKEN:-token_not_set}
server:
  forward-headers-strategy: FRAMEWORK
  port: 8081

---
spring:
  config:
    import: db-e2e.properties
    activate:
      on-profile: e2e
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${INPUT_DB_URL:jdbc:mysql://127.0.0.1:3309/doughnut_e2e_test}
    username: ${db.user}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-on-validation-error: false
    clean-disabled: true
  jpa:
    generate-ddl: false
    show-sql: false
    properties.hibernate:
      enable_lazy_load_no_trans: true
      globally_quoted_identifiers: true
      globally_quoted_identifiers_skip_column_definitions: true
    open-in-view: false
  github_for_issues:
    repo: nerds-odd-e/doughnut_sandbox
    token: ${GITHUB_FOR_ISSUES_API_TOKEN:-token_not_set}
server:
  forward-headers-strategy: FRAMEWORK
  port: 9081

---
spring:
  config:
    activate:
      on-profile: prod
  resources:
    cache:
      cachecontrol:
        max-age: 365d
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://db-server:3306/doughnut
    username: doughnut
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-on-validation-error: false
    clean-disabled: true
  jpa:
    generate-ddl: false
    show-sql: false
    properties.hibernate:
      enable_lazy_load_no_trans: true
      globally_quoted_identifiers: true
      globally_quoted_identifiers_skip_column_definitions: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${OAUTH2_github_client_id}
            clientSecret: ${OAUTH2_github_client_secret}
  github_for_issues:
    repo: nerds-odd-e/doughnut
    token: ${GITHUB_FOR_ISSUES_API_TOKEN}
server:
  error:
    include-stacktrace: never
  forward-headers-strategy: FRAMEWORK
